[package]
name = "contracts-debugger"
version = "0.1.0"
authors = ["tobiasruck <ruck.tobias@gmail.com>"]
edition = "2018"

[dependencies]
cashcontracts = {"path"="../cryptopandas/cashcontracts-rs"}
secp256k1 = "0.15.5"
byteorder = "1.3.1"
text_io = "0.1.7"
hex = "0.3.2"
hex-literal = "0.2.1"
